version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/mattermost/mattermost-developer-documentation
    docker:
      - image: circleci/golang:1.11

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: mkdir bin
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
            echo "export PATH=$PATH:bin" >> $BASH_ENV
            echo "export HUGO_VERSION='0.58.3'" >> $BASH_ENV
            source $BASH_ENV
      - run: wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
      - run: tar -xvf /tmp/hugo.tar.gz hugo && mv hugo bin
      - run: make dist

      - persist_to_workspace:
          root: ~/Sites/mattermost-developer-documentation
          paths:
            - site/data

workflows:
  version: 2
  build:
    jobs:
      - build
