version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12-node

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
            echo "export PATH=$PATH:$PWD/bin" >> $BASH_ENV
            echo "HUGO_VERSION='0.58.3'" >> $BASH_ENV
            echo "GO111MODULE=on" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: build Hugo
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
            tar -xvf /tmp/hugo.tar.gz hugo
            sudo mv hugo /usr/bin/
      - run: make dist

workflows:
  version: 2
  ci:
    jobs:
      - build
