version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    steps:
      - checkout
      - run:
          name: build Hugo
          environment:
            HUGO_VERSION: 0.58.3
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
            tar -xvf /tmp/hugo.tar.gz hugo
            sudo mv hugo /usr/bin/
      - run: make dist

workflows:
  version: 2
  ci:
    jobs:
      - build
