version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: clone-mattermost-server
          command: |
            mkdir -p $GOPATH/src/github.com/mattermost/
            git clone https://github.com/mattermost/mattermost-server.git $GOPATH/src/github.com/mattermost/mattermost-server
            cd $GOPATH/src/github.com/mattermost/mattermost-server
            git reset --hard v5.17.1
      - run: mkdir -p site/data
      - run: go run scripts/plugin-godocs.go > site/data/PluginGoDocs.json
      - run: go run scripts/plugin-manifest-docs.go > site/data/PluginManifestDocs.json

workflows:
  version: 2
  ci:
    jobs:
      - build
