version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  ubuntu:
    working_directory: ~/go/src/github.com/mattermost/
    machine:
      image: "ubuntu-1604:201903-01"
    environment:
      COMPOSE_PROJECT_NAME: "circleci"

jobs:
  setup:
    working_directory: /go/src/github.com/mattermost/mattermost-server
    docker:
      - image: mattermost/mattermost-build-webapp:oct-2-2018
    steps:
      - checkout
      - run: |
          cd ../
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone --depth=1 git@github.com:mattermost/mattermost-webapp.git
          cd mattermost-webapp
          git checkout $CIRCLE_BRANCH || git checkout master
          export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
          echo "$WEBAPP_GIT_COMMIT"
          export CURL_FAILED=0
          if [ $CURL_FAILED -eq 1 ]
          then
            make build
          fi
      - persist_to_workspace:
          root: /go/src/github.com/mattermost
          paths:
            - mattermost-webapp
            - mattermost-server

  build:
    docker:
      - image: mattermost/mattermost-build-server:oct-18-2019
    working_directory: /go/src/github.com/mattermost/mattermost-developer-documentation
    steps:
      - attach_workspace:
          at: /go/src/github.com/mattermost/
      - checkout
      - run: make dist
      - persist_to_workspace:
          root: /go/src/github.com/mattermost
          paths:
            - mattermost-server
            - mattermost-webapp
workflows:
  version: 2
  untagged-build:
    jobs:
      - setup
      # - check-i18n:
      #     requires:
      #       - setup
      - build:
          requires:
            - setup
