version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
    - "/go/pkg/mod"

commands:
  check-uncommitted:
    description: Check for uncommitted changes.
    steps:
      - run:
          name: Check for uncomitted changes using git porcelain command.
          command: |
            if [[ `git status --porcelain` ]]; then
              echo "ERROR: uncommitted changes"
              git status --porcelain
              exit 1
            fi

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: mkdir -p $GOPATH/src/github.com/mattermost/ && git clone https://github.com/mattermost/mattermost-server.git $GOPATH/src/github.com/mattermost/mattermost-server && cd $GOPATH/src/github.com/mattermost/mattermost-server && git reset --hard v5.17.1
      - run: GO111MODULE=off go get -u -fix github.com/mattermost/mattermost-server/...
      - run: mkdir -p $GOPATH/src/go.uber.org && cd $GOPATH/src/go.uber.org && git clone https://github.com/uber-go/zap.git $GOPATH/src/go.uber.org/zap && git clone https://github.com/uber-go/atomic $GOPATH/src/go.uber.org/atomic
      - run: mkdir -p $GOPATH/src/go.uber.org && cd $GOPATH/src/go.uber.org && git clone https://github.com/uber-go/multierr.git $GOPATH/src/go.uber.org/multierr
      - run: mkdir -p $GOPATH/src/hashicorp && git clone https://github.com/hashicorp/go-hclog.git $GOPATH/src/hashicorp/go-hclog
      - run: sudo chown -vR $(whoami) $GOPATH
      - run: GO111MODULE=auto make dist
      - check-uncommitted
      - *save_cache

workflows:
  version: 2
  ci:
    jobs:
      - build
